apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
spec:
  template:
    spec:
      containers:
      - name: label-studio
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio-worker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"