apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
spec:
  template:
    spec:
      containers:
      - name: label-studio
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio-worker
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"