apiVersion: v1
kind: ConfigMap
metadata:
  name: label-studio-config
data:
  DJANGO_DB_ENGINE: "django.db.backends.postgresql_psycopg2"
  POSTGRES_HOST: "postgresql-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "labelstudio"
  POSTGRES_DB: "labelstudio"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: label-studio-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: bGFiZWxzdHVkaW8=  # labelstudio
  LABEL_STUDIO_USERNAME: YWRtaW4=       # admin
  LABEL_STUDIO_PASSWORD: YWRtaW4=       # admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio
  labels:
    app: label-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio
  template:
    metadata:
      labels:
        app: label-studio
    spec:
      containers:
      - name: label-studio
        image: heartexlabs/label-studio:1.14.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: label-studio-config
        - secretRef:
            name: label-studio-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: label-studio-service
spec:
  selector:
    app: label-studio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
---
apiVersion: batch/v1
kind: Job
metadata:
  name: label-studio-migrate
  labels:
    app: label-studio-migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: heartexlabs/label-studio:1.14.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
          - |
            python label_studio/core/manage.py migrate
            python label_studio/core/manage.py collectstatic --noinput
        envFrom:
        - configMapRef:
            name: label-studio-config
        - secretRef:
            name: label-studio-secrets
      restartPolicy: OnFailure
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-studio-worker
  labels:
    app: label-studio-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-studio-worker
  template:
    metadata:
      labels:
        app: label-studio-worker
    spec:
      containers:
      - name: worker
        image: heartexlabs/label-studio:1.14.0
        imagePullPolicy: IfNotPresent
        command: ["label-studio"]
        args: ["start", "worker"]
        envFrom:
        - configMapRef:
            name: label-studio-config
        - secretRef:
            name: label-studio-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "labelstudio"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: label-studio-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: "labelstudio"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - labelstudio
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - labelstudio
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379